version: 2
jobs:
  build-ami:
    docker:
      - image: hashicorp/packer:1.5.6
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build AMI
          command: ./buildAmi.sh
          
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-ami
